language: go
go:
- 1.16
services:
- docker
env:
  global:
    - secure: "K4QNT8iYx1aJvEIOTZI3zvue/ecNn05s1qB90wJlGhcSABEDqnxag7saLRaATvxSIm2tY7Zazr9cMkgvkK0GSQYPr8HcrMTY/0boZkePq3oomqG6H7Phezn5vZ3GdJqlmrWZ5OxZoq49TlVaydOJHYoYrDPg1WeLnt0Zt/TIDqvOh1DssWJYc+t0UqQRFRIFsUuNJqlf3HONHaEhqGMQpiufFDosPbaKOvnInU9sC10o6l6UNrrrxykhwsSxSSeG0bQZmcuPh5ZuIydCpE2uaHp24bsmN/5YpRyuildc3W0lY5RSvQyYHBkvhJrIfOoybWkb3b/0fHrbmNB1je5PDILHKtIHfa6sbqEr0j4GEFCuNbJB9fryD6ya8FzO6uwixZIHze17VHUDEFFgxOxhfxnoHUFXfaBuz6Giv5ptvgZJFFSc+ux66i1ZF9fv/sK7ganC5uQ7n428dppCWbuuvoRmkn6e0/Myk861YoBU7X0Xp2J6kX4j9mwiAlVaEwkGyqFgV0236yp2lGWQEEOHaicbUYKK2v93O3RgD6t//Sw6Bds+ENMm1GZAZoPWeWXH6kHYCl3jyxpgSGORGLKfVo7fy7YInglAPHqw4KtqjmKcQREAQLYg8/EyuPc8P9lG01n6KWTHo+rC5C9z0bEkeVflWXzDldIXf5SYXujAiH4="
    - secure: "WVLbMZa9OnI/CK8tbR9uFNa3prhrDTw87kkc1GNN4P6o3cMY53/oDnzX2bdXru+rPpcGSVhARcnHJaHev7W+Kr34JUeaYN4aHaC/WuRysljM44+kuD0thIwADrxmL5qSM9ix49wGP/30HpNqLnNULgEUnEkQ3YuIxCI6ilsr8VgsCxlD6mXlfNMEsZi9gQ5Pgysr30fginT0N6Hv+e0io9LyOL7D20f7AtifoKGddOC9HR+kC1ZsGF6ujMymEAP46YnW4AjWOC+K4uNd7CkMWQ4dGdP2o32CHPzdj0nIGsU39MsN5+KIeb8C5M8/XPQySllENLahxFXUxVKQHWptnkuBGMD4iB77ISP9dC4X23hws9SA27uCCBQW9Y+0/D1Qyggy5fG68Uj6U47xEhbsRzp9zatZzhTpfghDx7OtL4NY1MDyS+7J+sjayhB0AA/61X4IG8zGj/yuONHr6y4t2/64NSXnoLIFvslcvd5XwHtU+M6lfIJtjj+nXdR5XKnJqBIFVJ8jiCgu/Q9VCbxGKBSjWdBHysp7/m9AemEgfhCUY9ZVoXybTcSiQ8ILbgJGX7D/QcGz1BzpKz/es5qh1PHzC0TFQ6/5P6Fzj3SvG55DauxivF0zfMcPPT1HcC3vc+4Qv11sBZN4ZefnzUuFdq7/AVCURBjKyTOU6MsoI/w="
jobs:
  include:
  - stage: publish image
    name: Publish Docker image
    if: tag IS NOT blank
    before_script:
    - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    script:
    - make publish

